### PR TITLE
Added file extensions to modules

### PR DESCRIPTION
**Pull request by DanceParty**
Brought up in [Issue #3](https://github.com/Tyriar/hangul-romanization/issues/3)

### CODE REVIEW

**Comment by Tyriar** [comment]
Hmm, I've never run into this before with TypeScript. Some questions:

- Did you build using `npm install && npm run build`?
- How are using it? Does this error happen on build or when used on web/node?
- Does this change impact the output in `dist/`?

**Comment by DanceParty** [comment]
1. I was using yarn, installed with `yarn add hangul-romanization` and then `yarn install`. Maybe not running `yarn run build` will mess it up as I didn't do that, but not sure. I can try later.

2. Happens when used on node, not on build.

Sorry, this could be completely my bad, but I will test when I get home!

**Comment by Tyriar** [comment]
@jkd65 I suspect you may be including the typescript files from plain javascript. Doing a `require("hangul-romanization")` should pull in `dist/index.js` which is build from npm/yarn run build. Let me know if this is the case 😃

**Comment by DanceParty** [comment]
Yes I was trying to import into plain JavaScript. That being said, I used the `require('hangul-romanization')` with no success. do I also need to run `yarn build`?

**Comment by Tyriar** [comment]
@jkd65 hmm, I'll try look at this in the next couple of weeks. Super busy at work atm :sweat_smile:

**Comment by Tyriar** [comment]
The right fix was to fix the publishing of the package, more details here https://github.com/Tyriar/hangul-romanization/issues/3#issuecomment-304531654

**Pull request closed without merging**
